Dockerfile.ubuntu
doc/howto.rst

Fix: https://github.com/intel/media-delivery/issues/2

ffmpeg: switch to ffmpeg-n4.3 release

---

doc/howto.rst
samples/cdn/do-transcode.sh
samples/edge/do-transcode.sh
tests/demo.bats
tests/utils.bash

Fix: https://github.com/intel/media-delivery/issues/4

demo: support all video codecs in .mp4 container

---

.github/workflows/main.yml

ci: create github actions

---

Dockerfile.ubuntu

Fix: https://github.com/intel/media-delivery/issues/26

apt: install intel-gfx repo key

---

Dockerfile.ubuntu
doc/man/measure-perf.asciidoc

Fix: https://github.com/intel/media-delivery/issues/31

measure/perf: script keeps spawning helper tools

---

measure/performance/MSPerf.py

Fix: https://github.com/intel/media-delivery/issues/33

measure/perf: fix handling of mp4 streams

---

measure/quality/measure-quality

Fix: https://github.com/intel/media-delivery/issues/29

quality: handle out of bounds bdrate

---

measure/performance/MSPerf.py

Signed-off-by: James Iwan <james.iwan@intel.com>

measure performance: qsv_device command line fix.

---

measure/quality/AVC/run_cbr_ffmpeg-qsv.sh
measure/quality/AVC/run_vbr_ffmpeg-qsv.sh
measure/quality/HEVC/run_cbr_ffmpeg-qsv.sh
measure/quality/HEVC/run_vbr_ffmpeg-qsv.sh
measure/quality/measure-quality
samples/cdn/do-transcode.sh
samples/edge/do-transcode.sh
tests/consistency.bats
tests/demo.bats
tests/measure-perf.bats
tests/readme.rst
tests/utils.bash

fix multi-gpu in demo, measure-quality and tests

---

README.rst

docs: add link to intel container portal

---

measure/quality/measure-quality
tests/measure-quality.bats
tests/utils.bash

Signed-off-by: Socek, Daniel <daniel.socek@intel.com>

tests: add vdenc quality tests

---

doc/man/measure-perf.asciidoc
measure/performance/MSPerf.py
measure/performance/isVdenc.sh
tests/measure-perf.bats

Signed-off-by: James Iwan <james.iwan@intel.com>

measure-perf: add vdenc feature.

---

Dockerfile.ubuntu
assets/demo
assets/info

We need self-built igt (to be able to select desired GPU device for intel_gpu_top) in anticipation of Intel discrete GPUs support.

demo: switch to self-built igt

---

README.rst

doc: drop png width limitation

---

.dockerignore
assets/info
docker/ubuntu20.04/intel-gfx/Dockerfile
docker/ubuntu20.04/native/Dockerfile
measure/performance/MSPerf.py
templates/manuals.m4
tests/utils.bash

This is range of minor fixes and improvements. From functional side the only noticeable change is for measure-perf scripts for sample-decode path where application had backward incompatible change in options s/-f/-fps/. Other changes are to improve docker build process and tests.

Range of minor fixes

---

docker/ubuntu20.04/intel-gfx/Dockerfile
docker/ubuntu20.04/native/Dockerfile
templates/intel-gpu-tools.m4

igt: update to igt@1869d560

---

docker/ubuntu20.04/intel-gfx/Dockerfile
templates/m4docker/components/intel-gfx.m4

docker: expose intel-gfx apt repo via build-arg

---

measure/quality/AVC/run_cbr_ffmpeg-qsv.sh
measure/quality/AVC/run_cbr_sample-multi-transcode.sh
measure/quality/AVC/run_vbr_ffmpeg-qsv.sh
measure/quality/AVC/run_vbr_sample-multi-transcode.sh
measure/quality/HEVC/run_cbr_ffmpeg-qsv.sh
measure/quality/HEVC/run_cbr_sample-multi-transcode.sh
measure/quality/HEVC/run_vbr_ffmpeg-qsv.sh
measure/quality/HEVC/run_vbr_sample-multi-transcode.sh
measure/quality/measure-quality
tests/measure-quality.bats

quality: add encTools support

---

measure/quality/measure-quality

quality: fix appending issues

---

README.rst
doc/features/ffmpeg/README.md
doc/features/ffmpeg/av1.md
doc/features/ffmpeg/h264.md
doc/features/ffmpeg/h265.md
doc/features/ffmpeg/mjpeg.md
doc/features/ffmpeg/mpeg2.md
doc/features/ffmpeg/vp8.md
doc/features/ffmpeg/vp9.md

doc: added ffmpeg-qsv capability tables

---

doc/features/ffmpeg/av1.md
doc/features/ffmpeg/h264.md
doc/features/ffmpeg/h265.md
doc/features/ffmpeg/mjpeg.md
doc/features/ffmpeg/mpeg2.md
doc/features/ffmpeg/vp8.md
doc/features/ffmpeg/vp9.md

doc: add extra_hw_frames option to decoders option list

---

doc/features/ffmpeg/README.md
doc/features/ffmpeg/h264.md
doc/features/ffmpeg/h265.md

doc/ffmpeg: add encoders dynamic options

---

doc/features/ffmpeg/av1.md
doc/features/ffmpeg/h264.md
doc/features/ffmpeg/h265.md
doc/features/ffmpeg/vp9.md

n5.1 is out and we mark features appeared in it
See: https://github.com/FFmpeg/FFmpeg/releases/tag/n5.1

doc/ffmpeg: declare n5.1 features

---

docker/ubuntu20.04/dkms/Dockerfile
templates/m4docker/components/cse-backports.m4
templates/m4docker/components/pmt-backports.m4

Issue: intel/media-delivery#83
CSE and PMT DKMS git projects got history rewrite to fix some
issues. So, commit ids got altered. This commit resotres
status quo.

dkms: fix commit ids

---

doc/features/ffmpeg/h264.md

doc: correct description of h264 intra refresh

---

README.rst
doc/intel-gpu-dkms.rst

doc: add hardware requirements and highlight branding names

---

doc/features/ffmpeg/h264.md
doc/features/ffmpeg/h265.md

doc/ffmpeg: add -scenario and -adaptive_i/b description

---

README.rst

doc: landing page enctools update

---

doc/features/ffmpeg/README.md
doc/features/ffmpeg/h264.md
doc/features/ffmpeg/h265.md

doc/ffmpeg: add new available dynamic encoding settings

---

doc/quality-lowdelay.rst
doc/quality.rst
measure/quality/measure-quality

doc: update quality documentation with low delay

---

README.rst
doc/virtualization.rst

doc: document virtualization setup (passthrough & sriov)

---

README.rst

doc: update readme for better setup instruction

---

doc/performance.rst
doc/quality.rst

doc: add links to ATS-M and DG1 benchmarks from quality/performance.rst

---

doc/features/ffmpeg/h264.md
doc/features/ffmpeg/h265.md

doc/ffmpeg: add dynamic bitrate, framerate, sei settings

---

README.rst
doc/benchmarking.rst
doc/demo.rst
doc/docker.rst
doc/performance.rst
doc/reference-command-lines.rst

This patch improves top level documentation focusing on easy examples and moving more difficult stuff to separate documents.

doc: update project documentation

---

doc/quality.rst
doc/reference-command-lines.rst
measure/quality/measure-quality
scripts/ffmpeg-qsv-AV1-1080p.sh
scripts/ffmpeg-qsv-AV1-4K.sh
scripts/sample-multi-transcode-AV1-1080p.sh
scripts/sample-multi-transcode-AV1-4K.sh
tests/measure-quality.bats

With this change we start switch to AV1 enctools command lines which should give better quality for AV1 encoding.

measure/quality: Switch to AV1 enctools cmdlines

---

README.rst

doc: fix typo in .sh instruction

---

doc/features/ffmpeg/README.md
doc/features/ffmpeg/h264.md
doc/features/ffmpeg/h265.md

doc/ffmpeg: add new skip_frame and tier options

---

README.rst
scripts/sample-multi-transcode-AV1-8K-hyperenc1gpu.sh
scripts/sample-multi-transcode-AV1-8K-hyperenc2gpu.sh
scripts/sample-multi-transcode-HEVC-8K-hyperenc1gpu.sh
scripts/sample-multi-transcode-HEVC-8K-hyperenc2gpu.sh

examples: add 8k hyperencode examples

---

doc/intel-gpu-dkms.rst

doc: fix typo in doc/intel-gpu-dkms.rst

---

doc/features/ffmpeg/av1.md

doc/ffmpeg: describe available av1 dynamic options

---

README.rst

doc: add more notes on docker setup

---

docker/ubuntu20.04/intel-gfx/Dockerfile
docker/ubuntu20.04/native/Dockerfile
docker/ubuntu20.04/selfbuild-prodkmd/Dockerfile
docker/ubuntu20.04/selfbuild/Dockerfile
docker/ubuntu22.04/intel-gfx/Dockerfile
templates/intel-gpu-tools.m4

v1.27.x series is the first tagged series officially supporting discrete GPUs.
Issue: VSMGWL-62119

docker/igt: update to v1.27.1

---

doc/benchmarks/intel-iris-xe-max-graphics/intel-iris-xe-max-graphics.md
doc/quality-lowdelay.rst
doc/quality.rst
measure/quality/AV1/run_cbr_ffmpeg-qsv-ld.sh
measure/quality/AV1/run_cbr_ffmpeg-qsv.sh
measure/quality/AV1/run_cbr_ffmpeg-ref-ld.sh
measure/quality/AV1/run_cbr_ffmpeg-ref.sh
measure/quality/AV1/run_vbr_ffmpeg-qsv.sh
measure/quality/AV1/run_vbr_ffmpeg-ref.sh
measure/quality/AVC/run_cbr_ffmpeg-qsv-ld.sh
measure/quality/AVC/run_cbr_ffmpeg-qsv.sh
measure/quality/AVC/run_cbr_ffmpeg-ref-ld.sh
measure/quality/AVC/run_cbr_ffmpeg-ref.sh
measure/quality/AVC/run_vbr_ffmpeg-qsv.sh
measure/quality/AVC/run_vbr_ffmpeg-ref.sh
measure/quality/HEVC/run_cbr_ffmpeg-qsv-ld.sh
measure/quality/HEVC/run_cbr_ffmpeg-qsv.sh
measure/quality/HEVC/run_cbr_ffmpeg-ref-ld.sh
measure/quality/HEVC/run_cbr_ffmpeg-ref.sh
measure/quality/HEVC/run_vbr_ffmpeg-qsv.sh
measure/quality/HEVC/run_vbr_ffmpeg-ref.sh
measure/quality/measure-quality
patches/ffmpeg/0001-lavfi-vf_vpp_qsv-set-the-right-timestamp-for-AVERROR.patch

Issue: https://trac.ffmpeg.org/ticket/10261
Issue: https://trac.ffmpeg.org/ticket/10262
* Cherry-picking ffmpeg fix for above 2 issues (from release/6.0 branch:  https://github.com/FFmpeg/FFmpeg/commit/a3c93c03adf3ba5eaf17a5acf85b9a324c8cabe7)
* Replace `-r` with `--framerate` for rawvideo

Add bugfixes in scripts and ffmpeg

---

doc/benchmarks/intel-iris-xe-max-graphics/intel-iris-xe-max-graphics.md
doc/quality-lowdelay.rst
doc/quality.rst
measure/quality/AV1/run_cbr_ffmpeg-qsv-ld.sh
measure/quality/AV1/run_cbr_ffmpeg-qsv.sh
measure/quality/AV1/run_cbr_ffmpeg-ref-ld.sh
measure/quality/AV1/run_cbr_ffmpeg-ref.sh
measure/quality/AV1/run_vbr_ffmpeg-qsv.sh
measure/quality/AV1/run_vbr_ffmpeg-ref.sh
measure/quality/AVC/run_cbr_ffmpeg-qsv-ld.sh
measure/quality/AVC/run_cbr_ffmpeg-qsv.sh
measure/quality/AVC/run_cbr_ffmpeg-ref-ld.sh
measure/quality/AVC/run_cbr_ffmpeg-ref.sh
measure/quality/AVC/run_vbr_ffmpeg-qsv.sh
measure/quality/AVC/run_vbr_ffmpeg-ref.sh
measure/quality/HEVC/run_cbr_ffmpeg-qsv-ld.sh
measure/quality/HEVC/run_cbr_ffmpeg-qsv.sh
measure/quality/HEVC/run_cbr_ffmpeg-ref-ld.sh
measure/quality/HEVC/run_cbr_ffmpeg-ref.sh
measure/quality/HEVC/run_vbr_ffmpeg-qsv.sh
measure/quality/HEVC/run_vbr_ffmpeg-ref.sh
measure/quality/measure-quality
patches/ffmpeg/0001-lavfi-vf_vpp_qsv-set-the-right-timestamp-for-AVERROR.patch

Issue: https://trac.ffmpeg.org/ticket/10261
Issue: https://trac.ffmpeg.org/ticket/10262
* Cherry-picking ffmpeg fix for above 2 issues (from release/6.0 branch: https://github.com/FFmpeg/FFmpeg/commit/a3c93c03adf3ba5eaf17a5acf85b9a324c8cabe7)
* Replace -r with --framerate for rawvideo

[release/3.1] bugfixes in scripts and ffmpeg

---

doc/man/measure-quality.asciidoc
measure/quality/HEVC/run_cbr_ffmpeg-qsv-ld.sh
measure/quality/HEVC/run_cbr_ffmpeg-qsv.sh
measure/quality/HEVC/run_vbr_ffmpeg-qsv.sh
measure/quality/measure-quality
tests/measure-quality.bats

quality: add HEVC 4:2:2 8b and 10b support
